### PR TITLE
Yaml parser

### PR DESCRIPTION
**Pull request by seb-mm**
I added a YamlParser class that can be accessed to retrieve the values of a given YAML key as a set.
This is supposed to make it easier to retrieve aliases as well in future development or any other YAML values associated to another key.

I ran pytest without errors and also the tests on my own testvault.

### CODE REVIEW

**Comment by danymat** [comment]
Nice, I will merge it. So we can use this class to retrieve information about every key in YAML?

**Comment by seb-mm** [comment]
Yes.
You just have to pass the key and the contents of a file to it (this is currently done:
- Parser `.searchFilesWithTag(key)` loops through `self.mdFiles`
- this parser method calls the `.findTags()` method from `MarkdownFile`
- in this method you read the contents of the current file
- the `YamlParser` is instantiated with the `key` (right now `"tags"`) and the `file contents` as parameters
- on that instance the `._findValueInYAML()` method is called
- then the result of it has to be returned, it will be in the form of a set)

For the `.findTags` method a set() needs to be declared before. Then the result of the YamlParser is set to this variable. Then the normal tags, if any, are added to it.
This is necessary because we need something to add the tags to in case there are no YAML tags.

I also think that this line (line 32) in `MarkdownFile.py` is unnecessary:
`value = None`

I do have plans to make the Regex more robust so that there can also be whitespace in the YAML.
(I can't just do that in the positive lookbehind, as Python Regex doesn't support unlimited characters in there, so I'll have to adjust the string manipulation accordingly and stop using the lookbehind.)

**Comment by seb-mm** [comment]
And I also have to take a look at how it handles `"text with special characters in quotes"` and adjust it if necessary.

**Comment by seb-mm** [comment]
I think I'll try to implement it with a package made for it and see how it goes.
Last time I tried to access packages for it it always failed, today it curiously seems to work.
Although there'll be one dependency more then. Let's see..

**Pull request merged**
