### PR TITLE
Yaml-tags Regex

### PR DESCRIPTION
**Pull request by seb-mm**
I've updated your code so that it will also find tags in YAML frontmatter.
I've tried it with my vault and it worked as I expected.

Please try it out yourself before merging, so as to make sure that I didn't introduce any bugs or unwanted behaviour.

### CODE REVIEW

**Comment by danymat** [comment]
Hello, thanks for contributing! It's an important feature the one you contributed !
I did some tests and I found a bug: 

- When I want to export a tag, for example `test`, if i start to write the tag, it will export the full tag anyways:

Capture d’écran 2021-02-08 à 08 25 13

Maybe the regex is too permissive

**Comment by seb-mm** [comment]
Ah yes, I see what the problem is.

I just checked whether the tag is in the result but not whether it equals it. I assumed that people would enter full tags, but I can see how that would mess with nested tags. I already have an idea on how to fix it, I'll just have to do some string manipulation depending on the match.
I'll try to give it a go today.

**Comment by seb-mm** [comment]
I think the best way would be to parse the yaml front matter, because using string manipulation would make the code messy and if we have yaml, we should also try to use it.
Let's see if I can get that implemented.

**Comment by seb-mm** [comment]
I've completely reworked the `_tagInCurrentFile` method and changed the Regex of `self._regexFindTags`.
Feel free to implement them in your current implementation, because I think you know best where you moved what.
I didn't change anything else.

**Comment by danymat** [comment]
I just committed some large restructuration in src, can you update your code with :

`git pull https://github.com/danymat/Obsidian-Extractor.git your_branch`

What you'll have to change is the file named `MarkdownFile` in `src/`. Caution: the function you worked on doesn't exist anymore, it is replaced by the function called `_findTags` which return all tags in Markdown File. 

If you do have any questions, feel free to ask !

(btw, i integrated some tests, this is the process:)
(run in a virtual environment if you don't wan't purest to be installed globally. If you already have pytest, skip 1)
1. `pip install -r requirements.txt`
2. `pytest test/`

**Comment by seb-mm** [comment]
Thanks for merging it, otherwise I would have tried it after having lunch with the instructions you gave. :)

**Comment by danymat** [comment]
No problem, I released a new version with your changes and the basic parser. 
You can use it to your projects, feel free to contribute

Thanks for all the work!

**Pull request merged**
