### PR TITLE
Yaml iterator

### PR DESCRIPTION
**Pull request by seb-mm**
I added a method that returns a dictionary of the yaml keys as string and its values as set.
I still have to add how it works to the Readme.

To illustrate how it works I've called it and added print statements to `_findTags` in `MarkdownFile.py`.
I'll update the docs later.

### CODE REVIEW

**Comment by seb-mm** [comment]
I updated the docs.
I have left the print statements in `_findTags` for you to test it out, though.

**Comment by seb-mm** [comment]
I think there's still a bug in the YamlParser for values in list form that have spaces in them. I'll have to look into that. (That's always been like it, so no change in this pull request.)

**Comment by seb-mm** [comment]
Now it also supports spaces in the yaml entries. This is especially useful for aliases.
`""` and `''` are stripped.

**Review by danymat — CHANGES_REQUESTED** [review]
If findValueInYAML() and iterateYAML can not be called from user, consider removing it from the readme example python script, and only keep findAllYAML (with removing underscore from this one).

Don't forget to make the changes in MarkdownFile (if you removed the underscore for findAllYAML

**Comment by seb-mm** [comment]
I changed the Readme, commented ~~out~~ the test for yaml iterator in `_findtags()` in `MarkdownFile` and removed the underscore.

**Review by danymat — APPROVED** [review]
Merged, Thanks!

**Pull request merged**
